import Head from "next/head";
import React, { ReactNode, Fragment } from "react";
import styled from "styled-components";
import Navbar from "./Navbar";

type LayoutProps = {
  children: ReactNode;
  fullWidth?: boolean;
};

const Main = styled.main<LayoutProps>`
  max-width: ${(props) => (props.fullWidth ? "100%" : "1200px")};
  margin: 0 auto;
  padding: ${(props) => props.theme.sizes.s5};
  p,
`;

export default function Layout({ children, fullWidth = false }: LayoutProps) {
  return (
    <Fragment>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!fullWidth ? <Navbar /> : null}

      <Main fullWidth={fullWidth}>{children}</Main>
    </Fragment>
  );
}
